//book_management function file
/************************************************************************
University of Leeds
School of Computing
COMP1921-  Programming Project
Coursework 2

I confirm that the following code has been developed and written by me and it is entirely the result of my own work.
I also confirm that I have not copied any parts of this program from another person or any other source or facilitated someone to copy this program from me.
I confirm that I will not publish the program online or share it with anyone without permission of the module leader.

Student Name: Shrawan Sreekumar
Student ID: 201398821
Email: el20ss@leeds.ac.uk
Date Work Commenced: 2nd February 2021
*************************************************************************/

#include <stdio.h>
#include <stdlib.h>
#include "book_management.h"

int store_books(FILE *file){

    //saves the database of books in the specified file
    //returns 0 if books were stored correctly, or an error code otherwise
}


int load_books(FILE *file){

    //loads the database of books from the specified file
    //the file must have been generated by a previous call to store_books()
    //returns 0 if books were loaded correctly, or an error code otherwise
}



int add_book(struct Book book){

    //adds a book to the ones available to the library
    //returns 0 if the book could be added, or an error code otherwise
}


int remove_book(struct Book book){

    //removes a book from the library
    //returns 0 if the book could be successfully removed, or an error code otherwise.
}


struct BookArray find_book_by_title (const char *title){

    //finds books with a given title.
    //returns a BookArray structure, where the field "array" is a newly allocated array of books, or null if no book with the 
    //provided title can be found. The length of the array is also recorded in the returned structure, with 0 in case
    //array is the null pointer.
}


struct BookArray find_book_by_author (const char *author){

    //finds books with the given authors.
    //returns a BookArray structure, where the field "array" is a newly allocated array of books, or null if no book with the 
    //provided title can be found. The length of the array is also recorded in the returned structure, with 0 in case
    //array is the null pointer.
}

struct BookArray find_book_by_year (unsigned int year){

    //finds books published in the given year.
    //returns a BookArray structure, where the field "array" is a newly allocated array of books, or null if no book with the 
    //provided title can be found. The length of the array is also recorded in the returned structure, with 0 in case
    //array is the null pointer.
}

//test main function
int main(){

    //testing code goes here

}
