#ifndef USER_MANAGEMENT_GUARD__H 
#define USER_MANAGEMENT_GUARD__H 

#include <stdio.h>
#define MAX_USERS 99

struct User{
        int ID; //user ID
		char* name; //user  name
		char* email; // user email : ensure @ symbol is present when taking input
		char* username; //user login username
        char* password; //user login password
        int isAdmin;
    };

extern struct User userbase[MAX_USERS]; //array of users
extern int numUsers;
 
//saves the database of users in the specified file
//returns 0 if users were stored correctly, or an error code otherwise
int store_users(FILE *file);

//loads the database of users from the specified file
//the file must have been generated by a previous call to store_books()
//returns 0 if users were loaded correctly, or an error code otherwise
int load_users(FILE *file);

//adds a users to the ones available to the database
//returns 0 if the users could be added, or an error code otherwise
int register_users(struct User* user, int type);

//allows existing users to login to access the main menu : returns 'a' if admin and 'u' if user
//returns 'f' if the user could not successfully login
struct User login_users(const char* username, const char* password);


//creates a new struct User newUser who can be added to the userbase
//returns null if the user could not be created
struct User* create_new_user();


#endif

