//user_management function file
/************************************************************************
University of Leeds
School of Computing
COMP1921 - Programming Project
Coursework 1

I confirm that the following code has been developed and written by me and it is entirely the result of my own work.
I also confirm that I have not copied any parts of this program from another person or any other source or facilitated someone to copy this program from me.
I confirm that I will not publish the program online or share it with anyone without permission of the module leader.

Student Name: Shrawan Sreekumar
Student ID : 201398821
Email: el20ss@leeds.ac.uk
Date Work Commenced: 5th February 2021
*************************************************************************/

#include "library_management.h"

//declaration
struct User usersbase[MAX_USERS]; 
int numUsers = 0;
char *output;
struct User* newUser; //holds the created user before registration
//***********************************************************************

int store_users(FILE *file){

//saves the database of users in the specified file
//returns 0 if users were stored correctly, or an error code otherwise
    if(file == NULL) return -1;
    else{
        static char tmpName[MAX_STRING];
        static char tmpEmail[MAX_STRING];
        static char tmpUsername[MAX_STRING];
        static char tmpPassword[MAX_STRING];

        fprintf(file,"%d\n",numUsers);
        for(int i=0; i<numUsers; i++){

            strcpy(tmpName,usersbase[i].name);
            strcpy(tmpEmail,usersbase[i].email);
            strcpy(tmpUsername,usersbase[i].username);
            strcpy(tmpPassword,usersbase[i].password);

            fprintf(file,"%d \t %s \n %s \n %s \n %s \n %d \n",
                        usersbase[i].ID, tmpName, tmpEmail, tmpUsername , tmpPassword, usersbase[i].isAdmin);

        }
        fclose(file);
        return 0;
    }
}


int load_users(FILE *file){ 

//loads the database of users from the specified file
//the file must have been generated by a previous call to store_books()
//returns 0 if users were loaded correctly, or an error code otherwise
    if(file == NULL) return -1;
    else{

        fscanf(file,"%d\n",&numUsers); 
        static char tmpName[MAX_STRING];
        static char tmpEmail[MAX_STRING];
        static char tmpUsername[MAX_STRING];
        static char tmpPassword[MAX_STRING];

        for(int i=0; i<numUsers; i++){

            fscanf(file,"%d \t",&usersbase[i].ID);
            fgets(tmpName,MAX_STRING,file);
            fgets(tmpEmail,MAX_STRING,file);
            fgets(tmpUsername,MAX_STRING,file);
            fgets(tmpPassword,MAX_STRING,file);

            fscanf(file,"%d\n",&usersbase[i].isAdmin);

            tmpName[strcspn(tmpName,"\n")] = 0;
            tmpEmail[strcspn(tmpEmail,"\n")] = 0;
            tmpUsername[strcspn(tmpUsername,"\n")] = 0;
            tmpPassword[strcspn(tmpPassword,"\n")] = 0;

            usersbase[i].name = strdup(tmpName);
            usersbase[i].email = strdup(tmpEmail);
            usersbase[i].username = strdup(tmpUsername);
            usersbase[i].password = strdup(tmpPassword);
            
        }
        fclose(file);
        return 0;
    }
}


struct User* create_new_user(){
    //creates a new struct User newUser who can be added to the usersbase
    //returns null if the user could not be created

    newUser = (struct User*)malloc(sizeof(struct User*));

    printf("\n*Create New User*");

    newUser->ID = numUsers + 1;
    newUser->name = returnString("\n>>>Enter new user name : ");
        free(output);
    newUser->email = returnString("\n>>>Enter new user email : ");
        free(output);
    newUser->username = returnString("\n>>>Enter new login username : ");
        free(output);
    printf("\n*Ensure password is at least 6 characters long!*");
    newUser->password = returnString("\n>>>Enter new login password : ");
        free(output);

    newUser->isAdmin = 0;

    return newUser;

}


int register_users(struct User* user, int type){
    //adds a users to the ones available to the database
    //returns 0 if the users could be added, or an error code otherwise
    if(user->name == NULL){//name checks
        printf("\nName field cannot be empty");
        return -1;
    }

    if(user->email == NULL){//email checks
        printf("\nEmail field cannot be empty");
        return -1;
    }
    else if( strstr(user->email, "@") == NULL){
        printf("\nEmail not in acceptable format : Missing '@' ");
        return -1;
    }

    if(user->username == NULL){//username check
        printf("\nUsername field cannot be empty");
        return -1;
    }

    if(user->password == NULL){//password check
        printf("\nPassword field cannot be empty");
        return -1;
    }
    else if(strlen(user->password) < 8){
        printf("\nPassword not long enough");
        return -1;
    }
    
    usersbase[numUsers].ID = user->ID;
    usersbase[numUsers].name = user->name;
    usersbase[numUsers].email = user->email;
    usersbase[numUsers].username = user->username;
    usersbase[numUsers].password = user->password;

    user->isAdmin = type;
    usersbase[numUsers].isAdmin = user->isAdmin;
    numUsers++;
    free(newUser);
    printf("\nSuccessfully Added User!");
    return 0;
}


struct User login_users(const char* username, const char* password){
    //allows existing users to login to access the main menu
    //returns f if the user could not successfully login
    struct User returnNull;
    returnNull.username = NULL;

    if( username == NULL ) return returnNull;
    else if( password == NULL ) return returnNull;

    else{
        //find username and password in usersbase
        for( int i = 0; i<numUsers; i++){

            if( strcmp(username, usersbase[i].username) == 0){
                if( strcmp(password, usersbase[i].password) == 0){
                    if( usersbase[i].isAdmin == 1){
                        printf("\nWelcome Admin");
                        return usersbase[i];
                    }
                    else{
                        printf("\nWelcome %s",usersbase[i].name);
                        return usersbase[i];
                    }
                }
            }
        }

        printf("\n *User not found* ");     
        return returnNull;
    }

}


