//user_management function file
/************************************************************************
University of Leeds
School of Computing
COMP1921 - Programming Project
Coursework 1

I confirm that the following code has been developed and written by me and it is entirely the result of my own work.
I also confirm that I have not copied any parts of this program from another person or any other source or facilitated someone to copy this program from me.
I confirm that I will not publish the program online or share it with anyone without permission of the module leader.

Student Name: Shrawan Sreekumar
Student ID : 201398821
Email: el20ss@leeds.ac.uk
Date Work Commenced: 5th February 2021
*************************************************************************/

#include "library_management.h"


//declaration
// struct Book *library[stockSize]; //uncomment only for tests
// int numBooks;

//***********************************************************************


int store_users(FILE *file){

    //saves the array of users in the specified file
    //returns 0 if users were stored correctly, or an error code otherwise
    if(file == NULL) return -1;
    else{
        
        fwrite(&numUsers,sizeof(int),1,file);
        fwrite(&users,sizeof(struct Book),numBooks,file);

        return 0;
    }
}


int load_users(FILE *file){

    //loads the array of users from the specified file
    //the file must have been generated by a previous call to store_books()
    //returns 0 if users were loaded correctly, or an error code otherwise

    if(file == NULL) return -1;
    else{
        free(users);
        *users = (struct User*)malloc(sizeof(struct User*)*stockSize);

        fread(&numUsers,sizeof(int),1,file);
        fread(&users,sizeof(struct Book),numBooks,file); //dont forget to free the *library array

        return 0;
    }
}


int add_users(struct User newUser){

    //code to add new user
}


int remove_users(struct User newUser){

    //code to remove user
}


int borrow_book(struct User borrower){

    //code for when user borrows book
}


int return_book(struct User returner){

    //code for when user returns book
}

// int main(){
//     //skeleton framework
// }